import type { DashboardData, RiskLevel } from "./types";

const now = new Date();
const iso = (minutesAgo: number) => new Date(now.getTime() - minutesAgo * 60_000).toISOString();

export const levelOrder: Record<RiskLevel, number> = {
  LOW: 0,
  MEDIUM: 1,
  HIGH: 2,
  CRITICAL: 3,
};

export const demoData: DashboardData = {
  status: {
    running: true,
    watch_dirs: ["experiments/sandbox"],
    uptime_seconds: 1860,
    events_processed: 128,
    queue_size: 0,
    events_total: 128,
    alerts_total: 18,
    highest_level: "CRITICAL",
    last_event_time: iso(1),
    last_alert_time: iso(2),
    analyzers_enabled: 6,
    snapshot_available: true,
    report_available: true,
  },
  alerts: {
    total: 18,
    by_level: { LOW: 3, MEDIUM: 5, HIGH: 6, CRITICAL: 4 },
    alerts: [
      {
        timestamp: iso(2),
        event_type: "modified",
        src_path: "experiments/sandbox/restore_target/doc_03.txt",
        dest_path: null,
        score: 9.26,
        level: "CRITICAL",
        analyzers: ["EntropyAnalyzer", "FuzzyHashAnalyzer", "HoneypotSentinel"],
        signal_types: ["entropy_anomaly", "similarity_drop", "honeypot_touched"],
        escalated: false,
        escalation_reason: null,
        signals: [
          {
            analyzer_name: "EntropyAnalyzer",
            signal_type: "entropy_anomaly",
            value: 8.9,
            weight: 3,
            evidence: { entropy_before: 4.31, entropy_after: 7.86, threshold: 6.5 },
            timestamp: iso(2),
          },
          {
            analyzer_name: "FuzzyHashAnalyzer",
            signal_type: "similarity_drop",
            value: 9.1,
            weight: 3,
            evidence: { similarity: 0.03, threshold: 0.3 },
            timestamp: iso(2),
          },
        ],
      },
      {
        timestamp: iso(7),
        event_type: "created",
        src_path: "experiments/sandbox/certificates/service.key",
        dest_path: null,
        score: 5,
        level: "HIGH",
        analyzers: ["SensitivePathAnalyzer"],
        signal_types: ["policy_hit"],
        escalated: true,
        escalation_reason: "policy_hit reached 3 alerts within 60s",
        signals: [
          {
            analyzer_name: "SensitivePathAnalyzer",
            signal_type: "policy_hit",
            value: 4.6,
            weight: 2,
            evidence: { policy: "certificate-and-key", pattern: "**/*.key" },
            timestamp: iso(7),
          },
        ],
      },
      {
        timestamp: iso(15),
        event_type: "modified",
        src_path: "experiments/sandbox/financial/budget_2024.csv",
        dest_path: null,
        score: 4.4,
        level: "MEDIUM",
        analyzers: ["SensitivePathAnalyzer"],
        signal_types: ["policy_hit"],
        escalated: false,
        escalation_reason: null,
        signals: [
          {
            analyzer_name: "SensitivePathAnalyzer",
            signal_type: "policy_hit",
            value: 4.4,
            weight: 2,
            evidence: { policy: "financial", work_hours: false },
            timestamp: iso(15),
          },
        ],
      },
    ],
  },
  events: {
    total: 128,
    events: [
      {
        timestamp: iso(1),
        event_type: "modified",
        src_path: "experiments/sandbox/restore_target/doc_03.txt",
        dest_path: null,
        file_size: 32768,
        is_directory: false,
        score: 9.26,
        level: "CRITICAL",
        signals_count: 3,
      },
      {
        timestamp: iso(3),
        event_type: "moved",
        src_path: "experiments/sandbox/restore_target/doc_02.txt",
        dest_path: "experiments/sandbox/restore_target/doc_02.txt.locked",
        file_size: 32768,
        is_directory: false,
        score: 8.4,
        level: "CRITICAL",
        signals_count: 2,
      },
      {
        timestamp: iso(7),
        event_type: "created",
        src_path: "experiments/sandbox/certificates/service.key",
        dest_path: null,
        file_size: 1024,
        is_directory: false,
        score: 5,
        level: "HIGH",
        signals_count: 1,
      },
      {
        timestamp: iso(18),
        event_type: "modified",
        src_path: "experiments/sandbox/normal/readme.txt",
        dest_path: null,
        file_size: 2048,
        is_directory: false,
        score: 1.2,
        level: "LOW",
        signals_count: 0,
      },
    ],
  },
  analyzers: {
    total: 6,
    items: [
      { name: "SensitivePathAnalyzer", enabled: true, weight: 2, signals_total: 7, last_triggered_at: iso(7) },
      { name: "EntropyAnalyzer", enabled: true, weight: 3, signals_total: 4, last_triggered_at: iso(2) },
      { name: "FrequencyAnalyzer", enabled: true, weight: 2.5, signals_total: 3, last_triggered_at: iso(5) },
      { name: "HoneypotSentinel", enabled: true, weight: 5, signals_total: 1, last_triggered_at: iso(2) },
      { name: "HashDiffChecker", enabled: true, weight: 1.5, signals_total: 5, last_triggered_at: iso(3) },
      { name: "FuzzyHashAnalyzer", enabled: true, weight: 3, signals_total: 4, last_triggered_at: iso(2) },
    ],
  },
  snapshots: {
    enabled: true,
    baseline_file: ".fileguard/baseline.json",
    backup_dir: ".fileguard/backups",
    files_total: 42,
    last_snapshot_time: iso(25),
    last_restore_verified: true,
    incremental_total: 9,
    incremental_records: [
      {
        path: "experiments/sandbox/restore_target/doc_03.txt",
        old_hash: "8c4a71f0d89a",
        new_hash: "fb912ad49319",
        old_entropy: 4.31,
        new_entropy: 7.86,
        timestamp: iso(2),
        event_type: "modified",
      },
      {
        path: "experiments/sandbox/financial/budget_2024.csv",
        old_hash: "a62e118bc421",
        new_hash: "f28c917ab11e",
        old_entropy: 3.92,
        new_entropy: 4.05,
        timestamp: iso(15),
        event_type: "modified",
      },
    ],
    auto_restore_actions: [
      {
        timestamp: iso(1),
        path: "experiments/sandbox/restore_target/doc_03.txt",
        dry_run: true,
        restored: false,
        verified: false,
        reason: "dry-run candidate",
      },
    ],
  },
  reports: {
    ok: true,
    report_file: "experiments/sandbox/outputs/demo_report.html",
    available: true,
    generated_at: iso(4),
    events_total: 128,
    alerts_total: 18,
    error: null,
  },
};
