# -*- coding: utf-8 -*-
"""告警管理器。

管理告警的生成、去重、冷却和分发。
同一文件 + 同一信号类型在冷却期内不重复告警。
"""

from __future__ import annotations

import logging
from collections import defaultdict, deque
from datetime import datetime
from typing import Any

from fileguard.models import RiskAssessment

logger = logging.getLogger(__name__)


class AlertManager:
    """告警管理器。

    职责：
        接收 RiskAssessment，基于冷却期去重后记录至告警时间线。
        提供时间线查询接口供报告生成器使用。

    Attributes:
        cooldown_seconds: 同一 (路径, 信号类型) 组合的冷却时间（秒）。
    """

    def __init__(
        self,
        cooldown_seconds: float = 30.0,
        escalation_config: dict[str, Any] | None = None,
    ) -> None:
        """初始化告警管理器。

        Args:
            cooldown_seconds: 冷却时间（秒），默认 30 秒。
        """
        self.cooldown_seconds = cooldown_seconds
        self._last_alert: dict[tuple[str, str], datetime] = {}
        self._timeline: list[RiskAssessment] = []
        self._assessment_meta: dict[int, dict[str, Any]] = {}
        self._escalation_history: dict[str, deque[datetime]] = defaultdict(deque)
        config = escalation_config or {}
        self.escalation_enabled = bool(config.get("enabled", False))
        self.escalation_window_seconds = float(config.get("window_seconds", 60.0))
        self.escalation_threshold = int(config.get("threshold", 3))
        self.escalation_group_by = str(config.get("group_by", "signal_type"))
        self.escalations_total = 0

    def process(self, assessment: RiskAssessment) -> bool:
        """处理一条风险评估，决定是否发出告警。

        对评估中的每个信号检查冷却期，若所有信号均处于冷却中
        则抑制该条告警；否则记录到时间线并更新冷却状态。

        Args:
            assessment: 待处理的风险评估。

        Returns:
            True 表示该评估产生了新告警，False 表示被冷却抑制。
        """
        if not assessment.signals:
            return False

        now = assessment.timestamp
        has_new_signal = False

        for signal in assessment.signals:
            key = (assessment.event.src_path, signal.signal_type)
            last_time = self._last_alert.get(key)

            if last_time is None or (now - last_time).total_seconds() >= self.cooldown_seconds:
                self._last_alert[key] = now
                has_new_signal = True

        if has_new_signal:
            self._apply_escalation(assessment, now)
            self._timeline.append(assessment)
            logger.warning(
                "告警 [%s] %.2f — %s %s",
                assessment.level,
                assessment.score,
                assessment.event.event_type,
                assessment.event.src_path,
            )
            return True

        logger.debug(
            "告警被冷却抑制: %s %s",
            assessment.event.event_type,
            assessment.event.src_path,
        )
        return False

    def get_timeline(self) -> list[RiskAssessment]:
        """返回所有已记录的告警时间线。

        Returns:
            按时间顺序排列的 RiskAssessment 列表。
        """
        return list(self._timeline)

    def get_metadata(self, assessment: RiskAssessment) -> dict[str, Any]:
        """Return alert metadata generated by optional extensions."""
        return dict(self._assessment_meta.get(id(assessment), {}))

    def get_escalations(self) -> list[dict[str, Any]]:
        """Return timeline entries that were escalated by policy."""
        rows: list[dict[str, Any]] = []
        for assessment in self._timeline:
            meta = self._assessment_meta.get(id(assessment), {})
            if meta.get("escalated"):
                rows.append(
                    {
                        "timestamp": assessment.timestamp.isoformat(),
                        "src_path": assessment.event.src_path,
                        "from_level": meta.get("from_level"),
                        "to_level": assessment.level,
                        "reason": meta.get("escalation_reason"),
                    }
                )
        return rows

    def _apply_escalation(self, assessment: RiskAssessment, now: datetime) -> None:
        """Apply optional MEDIUM to HIGH escalation without changing process API."""
        if not self.escalation_enabled or assessment.level != "MEDIUM":
            return

        groups = self._escalation_groups(assessment)
        for group in groups:
            history = self._escalation_history[group]
            history.append(now)
            while history and (now - history[0]).total_seconds() > self.escalation_window_seconds:
                history.popleft()

            if len(history) >= self.escalation_threshold:
                old_level = assessment.level
                assessment.level = "HIGH"
                assessment.score = max(assessment.score, 5.0)
                self.escalations_total += 1
                self._assessment_meta[id(assessment)] = {
                    "escalated": True,
                    "from_level": old_level,
                    "to_level": assessment.level,
                    "escalation_reason": (
                        f"{group} reached {len(history)} alerts within "
                        f"{self.escalation_window_seconds:.0f}s"
                    ),
                }
                logger.warning(
                    "Alert escalated from %s to %s for %s (%s)",
                    old_level,
                    assessment.level,
                    assessment.event.src_path,
                    group,
                )
                return

    def _escalation_groups(self, assessment: RiskAssessment) -> list[str]:
        """Return escalation grouping keys for one assessment."""
        if self.escalation_group_by == "level":
            return [assessment.level]
        groups = sorted({signal.signal_type for signal in assessment.signals})
        return groups or [assessment.level]
